name: Publish image

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    tags: ["v*.*.*-post.*"]
  workflow_dispatch:

env:
  PACKAGE_REGISTRY: ghcr.io
  IMAGE_NAME: jks15satoshi/nekobox

jobs:
  push-image:
    name: Push image to registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag_variant: [latest, unstable]

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PACKAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch version info of NekoBox
        id: fetch_version
        run: |
          sudo apt install curl jq perl-base

          base_version=$(curl -s https://pypi.org/pypi/nekobox/json | jq -r ".info.version")

          if [[ "${{ matrix.tag_variant }}" == "unstable" ]]; then
            commit_sha=$(curl -s https://api.github.com/repos/wyapx/nekobox/commits/main | jq -r ".sha")

            version="main"
            tag_name="${base_version}+build.${commit_sha:0:7}"
          else
            version="${base_version}"
            tag_name="${base_version}"
          fi

          if [[ "${{ github.event_name }}" == "push" ]]; then
            rev_parsed=$(echo "${{ github.ref_name }}" | perl -pe 's/.*(?=rev.[[:digit:]]*)/\1/'
            tag_name="${tag_name}-${rev_parsed}"
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT

      - name: Check if image tag exists
        id: check_image_tag
        uses: tyriis/docker-image-tag-exists@v2.1.0
        with:
          registry: ghcr.io
          repository: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.fetch_version.outputs.tag_name }}

      - name: Build and push Docker image
        id: push_image
        uses: docker/build-push-action@v6
        if: ${{ steps.check_image_tag.outputs.tag == 'not found' }}
        with:
          context: .
          build-args: |
            "version=${{ steps.fetch_version.outputs.version }}"
          push: true
          tags: |
            ${{ env.PACKAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.fetch_version.outputs.tag_name }}
            ${{ env.PACKAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag_variant }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        if: ${{ steps.push_image.outcome == 'success' }}
        with:
          subject-name: ${{ env.PACKAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push_image.outputs.digest }}
          push-to-registry: true

      - name: Create release
        uses: ncipollo/release-action@v1
        if: ${{ matrix.tag_variant == 'latest' && steps.push_image.outcome == 'success' && github.event_name != 'push' }}
        with:
          tag: "v${{ steps.fetch_version.outputs.version }}"
          body: |
            ## 上游版本更新

            NekoBox 版本更新至 v${{ steps.fetch_version.outputs.version }}。
